Página de sorteos creada
biznaga-fest/web pull request #5
Opened 2023-10-15 10:50 UTC by daniolivet

2023-10-19 19:07 UTC, DavidRojoM requested changes

2023-10-19 19:07 UTC, DavidRojoM commented on src/components/Draw.astro
> +let rowClass = "flex-col sm:flex sm:flex-row gap-8 sm:gap-4 py-10";
use class:list instead. Eg

      class:list={{
        "class1 class2 class3": reverse,
      }}

2023-10-19 19:07 UTC, DavidRojoM commented on src/components/Draw.astro
rename it to raffle instead

2023-10-19 19:07 UTC, DavidRojoM commented on src/components/Navigation.astro
> +      <If condition={!!DATA.draws.length}>
rename to raffles

2023-10-19 19:07 UTC, DavidRojoM commented on src/components/Navigation.astro
> +          <a href="/draws" class="px-3"> Sorteos</a>
rename

2023-10-19 19:07 UTC, DavidRojoM commented on src/pages/draws/index.astro
> +<Layout title={"Sorteos"} description={""} lang="es">
Add description, remove braces

2023-10-20 07:30 UTC, daniolivet commented on src/components/Draw.astro
donete

2023-10-20 19:09 UTC, DavidRojoM requested changes

2023-10-20 19:09 UTC, DavidRojoM commented on src/components/Raffle.astro
> +console.log(reverse);
Remove console.log

2023-10-21 08:27 UTC, merged